### PR TITLE
Split into GApps and non-GApps

### PR DESCRIPTION
**Pull request by mr0ldphn**

### CODE REVIEW

**Comment by damolmo** [comment]
I need to build a fresh LineageOS 18.1 environment to test If everything builds as expected.
Don't forget to push changes on device specific and vendir trees too :)

**Comment by mr0ldphn** [comment]
Sure, I'm not entirely sure how to make pull requests for those, as they rely on new branches, but all forked repositories are ready to be merged

**Comment by mr0ldphn** [comment]
Yeah, you can't request to create a new branch in pull requests, I'm not sure how to solve it

**Comment by mr0ldphn** [comment]
For now I'll just make pull requests for the branches that are able to be merged

**Pull request closed without merging**
